image:
  repository: "sonarqube"
  tag: "6.7.3"
  pullPolicy: Always
#  pullsecret: artifactory.b6nonprod.read.secret
svc:
  name: sonarqube
cpurequest: 1 
cpulimit: 1 
memrequest: 1000Mi
memlimit: 1000Mi
volumesize: 10G
ingress: 
  host: sonarqube.test.com
tls:
  secretName: sonarqube
