apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ .Values.ingress.host }} 
spec:
  secretName: {{ .Values.tls.secretName }}
  issuerRef:
    name: letsencrypt
  commonName: {{ .Values.ingress.host }}
  dnsNames: 
  - {{ .Values.ingress.host }}
  acme:
    config:
    - http01:
       ingressClass: nginx
      domains:
      - {{ .Values.ingress.host }}
