apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sonarqube-app.releasename" . }} 
  labels:
    app: {{ template "sonarqube-app.releasename" . }}
data:
  sonar.properties: |+
    sonar.web.port=80880
