apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: {{ template "sonarqube-app.releasename" . }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.svc.name }} 
          servicePort: 80
        path: /
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.tls.secretName }}

